/*SET UP  AND DDL*/
CREATE DATABASE myDB;
USE myDB;

IF OBJECT_ID('Sale') IS NOT NULL
DROP TABLE SALE;

IF OBJECT_ID('Product') IS NOT NULL
DROP TABLE PRODUCT;

IF OBJECT_ID('Customer') IS NOT NULL
DROP TABLE CUSTOMER;

IF OBJECT_ID('Location') IS NOT NULL
DROP TABLE LOCATION;

GO

CREATE TABLE CUSTOMER (
CUSTID	INT
, CUSTNAME	NVARCHAR(100)
, SALES_YTD	MONEY
, STATUS	NVARCHAR(7)
, PRIMARY KEY	(CUSTID) 
);


CREATE TABLE PRODUCT (
PRODID	INT
, PRODNAME	NVARCHAR(100)
, SELLING_PRICE	MONEY
, SALES_YTD	MONEY
, PRIMARY KEY	(PRODID)
);

CREATE TABLE SALE (
SALEID	BIGINT
, CUSTID	INT
, PRODID	INT
, QTY	INT
, PRICE	MONEY
, SALEDATE	DATE
, PRIMARY KEY 	(SALEID)
, FOREIGN KEY 	(CUSTID) REFERENCES CUSTOMER
, FOREIGN KEY 	(PRODID) REFERENCES PRODUCT
);

CREATE TABLE LOCATION (
  LOCID	NVARCHAR(5)
, MINQTY	INTEGER
, MAXQTY	INTEGER
, PRIMARY KEY 	(LOCID)
, CONSTRAINT CHECK_LOCID_LENGTH CHECK (LEN(LOCID) = 5)
, CONSTRAINT CHECK_MINQTY_RANGE CHECK (MINQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_RANGE CHECK (MAXQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_GREATER_MIXQTY CHECK (MAXQTY >= MINQTY)
);

IF OBJECT_ID('SALE_SEQ') IS NOT NULL
DROP SEQUENCE SALE_SEQ;
CREATE SEQUENCE SALE_SEQ;



select name from sys.databases;

use myDB;


SELECT 
    *
FROM
    information_schema.tables;


SELECT NAME, MODIFY_DATE
FROM SYS.PROCEDURES;


SELECT *
FROM SYSOBJECTS
WHERE
XTYPE = 'U';



/*PROCEDURE 1*/
IF OBJECT_ID('ADD_CUSTOMER') IS NOT NULL
DROP PROCEDURE ADD_CUSTOMER;

GO
CREATE PROCEDURE ADD_CUSTOMER @PCUSTID INT, @PCUSTNAME NVARCHAR(100) AS

BEGIN
    BEGIN TRY

        IF @PCUSTID < 1 OR @PCUSTID > 499
            THROW 50020, 'Customer ID out of range', 1

        INSERT INTO CUSTOMER (CUSTID, CUSTNAME, SALES_YTD, STATUS) 
        VALUES (@PCUSTID, @PCUSTNAME, 0, 'OK');

    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 2627
            THROW 50010, 'Duplicate customer ID', 1
        ELSE IF ERROR_NUMBER() = 50020
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH;

END;

GO

EXEC ADD_CUSTOMER @PCUSTID = 1, @PCUSTNAME = 'David';

EXEC ADD_CUSTOMER @PCUSTID = 499, @PCUSTNAME = 'Oswald';

EXEC ADD_CUSTOMER @PCUSTID = 255, @PCUSTNAME = 'Nathan';

EXEC ADD_CUSTOMER @PCUSTID = 365, @PCUSTNAME = 'Larry';

EXEC ADD_CUSTOMER @PCUSTID = 500, @PCUSTNAME = 'Jessie';

SELECT * FROM CUSTOMER;

/*PROCEDURE 2*/
IF OBJECT_ID('DELETE_ALL_CUSTOMERS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_CUSTOMERS;
GO
CREATE PROCEDURE DELETE_ALL_CUSTOMERS AS 
BEGIN
  BEGIN TRY
    SELECT COUNT(*) AS "Rows Deleted" FROM CUSTOMER;
    DELETE FROM CUSTOMER;
  END TRY
  BEGIN CATCH
    BEGIN
    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
      THROW 50000, @ERRORMESSAGE, 1
    END;
  END CATCH;
END;

EXEC DELETE_ALL_CUSTOMERS;

/*PROCEDURE 3*/
IF OBJECT_ID('ADD_PRODUCT') IS NOT NULL
DROP PROCEDURE ADD_PRODUCT;

GO
CREATE PROCEDURE ADD_PRODUCT @PPRODID INT, @PPRODNAME NVARCHAR(100), @PPRICE MONEY AS

BEGIN
    BEGIN TRY

        IF @PPRODID < 1000 OR @PPRODID > 2500
            THROW 50040, 'Product ID out of range', 1
        IF @PPRICE < 0 OR @PPRICE > 999.99
            THROW 50050, 'Price out of range', 1

        INSERT INTO PRODUCT (PRODNAME, SELLING_PRICE, SALES_YTD, PRODID) 
        VALUES (@PPRODNAME, @PPRICE, 0, @PPRODID);

    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 2627
            THROW 50030, 'Duplicate product ID', 1
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END; 
    END CATCH;
END;

GO

EXEC ADD_PRODUCT @PPRODID = 1127, @PPRODNAME = 'PC', @PPRICE = 388;

EXEC ADD_PRODUCT @PPRODID = 2182, @PPRODNAME = 'Toilet Paper', @PPRICE = 12;

EXEC ADD_PRODUCT @PPRODID = 1333, @PPRODNAME = 'Crayon', @PPRICE = 5;

EXEC ADD_PRODUCT @PPRODID = 1876, @PPRODNAME = 'Spoon', @PPRICE = 24;

EXEC ADD_PRODUCT @PPRODID = 2007, @PPRODNAME = 'Water Bottle', @PPRICE = 34;

SELECT * FROM PRODUCT;

DELETE FROM PRODUCT;

/*PROCEDURE 4*/
IF OBJECT_ID('DELETE_ALL_PRODUCTS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_PRODUCTS;
GO
CREATE PROCEDURE DELETE_ALL_PRODUCTS AS 
BEGIN
  BEGIN TRY
    SELECT COUNT(*) AS "Rows Deleted" FROM PRODUCT;
    DELETE FROM PRODUCT;
  END TRY
  BEGIN CATCH
    BEGIN
    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
      THROW 50000, @ERRORMESSAGE, 1
    END;
  END CATCH;
END;

EXEC DELETE_ALL_PRODUCTS;

/*PROCEDURE 5*/

IF OBJECT_ID('GET_CUSTOMER_STRING') IS NOT NULL
DROP PROCEDURE GET_CUSTOMER_STRING;
GO
CREATE PROCEDURE GET_CUSTOMER_STRING @PCUSTID INT, @PRETURNSTRING NVARCHAR(1000) OUT AS
BEGIN
  BEGIN TRY
    DECLARE @CNAME NVARCHAR(100), @STATUS NVARCHAR(7), @SALESYTD MONEY;

    SELECT @CNAME = CUSTNAME, @STATUS = STATUS, @SALESYTD = SALES_YTD
    FROM CUSTOMER WHERE CUSTID = @PCUSTID;

    IF @@ROWCOUNT = 0 
      THROW 50060, 'Customer ID not found', 1
    ELSE
      SET @PRETURNSTRING = CONCAT('CustID: ', @PCUSTID, ' Name: ', @CNAME, ' Status: ', @STATUS, ' SalesYTD: ', @SALESYTD)
  END TRY
  BEGIN CATCH
    IF ERROR_NUMBER() = 50060
      THROW
    ELSE
      BEGIN
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
      END;
  END CATCH;
END;

GO
BEGIN
  DECLARE @OUTPUT NVARCHAR(1000);
  EXEC GET_CUSTOMER_STRING @PCUSTID = 1, @PRETURNSTRING = @OUTPUT OUT;
  PRINT @OUTPUT;
END;

GO

BEGIN
  DECLARE @OUTPUT NVARCHAR(1000);
  EXEC GET_CUSTOMER_STRING @PCUSTID = 99, @PRETURNSTRING = @OUTPUT OUT;
  PRINT @OUTPUT;
END;

/*PROCEDURE 6*/
IF OBJECT_ID('UPD_CUST_SALESYTD') IS NOT NULL
DROP PROCEDURE UPD_CUST_SALESYTD;
GO

CREATE PROCEDURE UPD_CUST_SALESYTD @PCUSTID INT, @PAMT MONEY AS

BEGIN
  BEGIN TRY
  IF @PAMT < -999.99 OR @PAMT > 999.99
    THROW 50080, 'Amount out of range', 1

  UPDATE CUSTOMER SET SALES_YTD = SALES_YTD + @PAMT
  WHERE CUSTID = @PCUSTID;

  IF @@ROWCOUNT = 0
  THROW 50070, 'Customer ID not found', 1

  END TRY
  BEGIN CATCH
    IF ERROR_NUMBER() IN (50070, 50080)
      THROW 
    ELSE
      BEGIN 
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END;
  END CATCH;
END;

SELECT * FROM CUSTOMER;

SELECT SALES_YTD FROM CUSTOMER WHERE CUSTID = 1;
EXEC UPD_CUST_SALESYTD @PCUSTID = 1, @PAMT = 100;
SELECT SALES_YTD FROM CUSTOMER WHERE CUSTID = 1;
EXEC UPD_CUST_SALESYTD @PCUSTID = 1, @PAMT = -50;
SELECT SALES_YTD FROM CUSTOMER WHERE CUSTID = 1;

EXEC UPD_CUST_SALESYTD @PCUSTID = 100, @PAMT = 50;
EXEC UPD_CUST_SALESYTD @PCUSTID = 1, @PAMT = 1000;
EXEC UPD_CUST_SALESYTD @PCUSTID = 1, @PAMT = -1000;

/*PROCEDURE 7*/
IF OBJECT_ID('GET_PROD_STRING') IS NOT NULL
DROP PROCEDURE GET_PROD_STRING;
GO
CREATE PROCEDURE GET_PROD_STRING @PPRODID INT, @PRETURNSTRING NVARCHAR(1000) OUT AS
BEGIN
  BEGIN TRY
    DECLARE @PNAME NVARCHAR(100), @PRICE NVARCHAR(7), @SALESYTD MONEY;

    SELECT @PNAME = PRODNAME, @PRICE = SELLING_PRICE, @SALESYTD = SALES_YTD
    FROM PRODUCT WHERE PRODID = @PPRODID;

    IF @@ROWCOUNT = 0 
      THROW 50090, 'Product ID not found', 1
    ELSE
      SET @PRETURNSTRING = CONCAT('ProdID: ', @PPRODID, ' Name: ', @PNAME, ' Price: ', @PRICE, ' SalesYTD: ', @SALESYTD)
  END TRY
  BEGIN CATCH
    IF ERROR_NUMBER() = 50090
      THROW
    ELSE
      BEGIN
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
      END;
  END CATCH;
END;

GO
BEGIN 
  DECLARE @OUTPUT NVARCHAR(1000);
  EXEC GET_PROD_STRING @PPRODID = 1127, @PRETURNSTRING = @OUTPUT OUT;
  PRINT @OUTPUT;
END;

GO
BEGIN
  DECLARE @OUTPUT NVARCHAR(1000);
  EXEC GET_PROD_STRING @PPRODID = 3232, @PRETURNSTRING = @OUTPUT OUT;
  PRINT @OUTPUT;
END;

/*PROCEDURE 8*/
IF OBJECT_ID('UPD_PROD_SALESYTD') IS NOT NULL
DROP PROCEDURE UPD_PROD_SALESYTD;
GO

CREATE PROCEDURE UPD_PROD_SALESYTD @PPRODID INT, @PAMT MONEY AS

BEGIN
  BEGIN TRY
  IF @PAMT < -999.99 OR @PAMT > 999.99
    THROW 50110, 'Amount out of range', 1

  UPDATE PRODUCT SET SALES_YTD = SALES_YTD + @PAMT
  WHERE PRODID = @PPRODID;

  IF @@ROWCOUNT = 0
  THROW 50100, 'Product ID not found', 1

  END TRY
  BEGIN CATCH
    IF ERROR_NUMBER() IN (50110, 50100)
      THROW 
    ELSE
      BEGIN 
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END;
  END CATCH;
END;


SELECT * FROM PRODUCT;

SELECT SALES_YTD FROM PRODUCT WHERE PRODID = 1127;
EXEC UPD_PROD_SALESYTD @PPRODID = 1127, @PAMT = 100;
SELECT SALES_YTD FROM PRODUCT WHERE PRODID = 1127;
EXEC UPD_PROD_SALESYTD @PPRODID = 1127, @PAMT = -50;
SELECT SALES_YTD FROM PRODUCT WHERE PRODID = 1127;

EXEC UPD_PROD_SALESYTD @PPRODID = 3232, @PAMT = 50;
EXEC UPD_PROD_SALESYTD @PPRODID = 1, @PAMT = 1000;
EXEC UPD_PROD_SALESYTD @PPRODID = 1, @PAMT = -1000;

/*PROCEDURE 9*/
IF OBJECT_ID('UPD_CUSTOMER_STATUS') IS NOT NULL
DROP PROCEDURE UPD_CUSTOMER_STATUS;
GO

CREATE PROCEDURE UPD_CUSTOMER_STATUS @PCUSTID INT, @PSTATUS NVARCHAR(7) AS

BEGIN
  BEGIN TRY
  IF @PSTATUS IS NOT 'OK' OR @PSTATUS IS NOT 'SUSPEND'
    THROW 50130, 'Invalid Status Value', 1

  UPDATE CUSTOMER SET STATUS = @PSTATUS
  WHERE CUSTID = @PCUSTID;

  IF @@ROWCOUNT = 0
  THROW 50120, 'Customer ID not found', 1

  END TRY
  BEGIN CATCH
    IF ERROR_NUMBER() IN (50070, 50080)
      THROW 
    ELSE
      BEGIN 
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END;
  END CATCH;
END;

/*PROCEDURE 10*/
